server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/business?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
mybatis:
  mapper-locations: classpath*:com/neuedu/business/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
